### ISSUE TITLE
Thesis Proposal supervisor selection

### ISSUE THREAD

**Issue by Sylvie-Molinatto** [Nico331/SE2-2023-G07_Thesis-Management#1]
When a teacher tries to insert a new thesis proposal, he should not select the supervisor because he can create a proposal just for himself.

**Comment by DarioMarchitelli** [comment]
And what if the one creating the proposal is one of the co-supervisor?

**Comment by Sylvie-Molinatto** [comment]
But the one who creates the thesis proposal is the supervisor, you cannot create a proposal as a co-supervisor

**Comment by DarioMarchitelli** [comment]
Thank you really much, we have been a bit superficial while reading the specifications.
