### ISSUE TITLE
Research groups selection 

### ISSUE THREAD

**Issue by Sylvie-Molinatto** [Nico331/SE2-2023-G07_Thesis-Management#2]
When a teacher tries to insert a new thesis proposal, he should not select the research groups because they are just those to which the supervisor and internal co-supervisors belong .

**Comment by DarioMarchitelli** [comment]
We would like to keep it like that because maybe a single thesis could be related to different groups (where one group could not be strictly related to the group of the supervisors)

**Comment by Sylvie-Molinatto** [comment]
<img width="408" alt="Screenshot 2023-11-24 092019" src="https://github.com/Nico331/SE2-2023-G07_Thesis-Management/assets/126864619/5c70619a-fc27-47a5-a21e-1df09338737c">
<img width="574" alt="Screenshot 2023-11-24 094015" src="https://github.com/Nico331/SE2-2023-G07_Thesis-Management/assets/126864619/71265e50-b8f9-484d-9783-043e2f2425ec">
